services:
  - type: web
    runtime: node
    name: mosaic-api
    rootDir: apps/api
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - fromGroup: mosaic-prod

  - type: web
    runtime: static
    name: mosaic-web
    rootDir: apps/web
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: dist
    envVars:
      - fromGroup: mosaic-prod-public
